### ISSUE TITLE
improve playability

### ISSUE THREAD

**Issue by kubamarkiewicz** [ChinosInternationalCC/chinoPinball#202]
Ideas how to improve playability:
- player should know the goal of the game. What is the goal? Is it to get the highest score? When we can add in the beginning of new game: "Get as many points as you can!"
- feedback: player should know if he win or not. We can save the highest score and in the moment when the player beats the record we can play a special sound and display "You have beaten the last record!". And at the end of the game: "Your score is: 123. Congrats, you got the highest score!". Or if you don't win: "Your score is: 10. The highest score is 123. Try again!". Or we can display the record all the time.
- If the game is too easy, it's no fun. We can increase difficulty when the score increases. For example we can increase gravity force (the ball will go faster) or we can add more balls to make it more interesting.

**Comment by carlesgutierrez** [comment]
Nice ideas! Lets add them to issues then.
